#ifndef FUNCIONESMERCADERIAS_H_INCLUDED
#define FUNCIONESMERCADERIAS_H_INCLUDED

/// PROTOTIPOS DE FUNCIONES PARA EL MENU DE MERCADERIAS
void registrarMercaderia();

#endif // FUNCIONESMERCADERIAS_H_INCLUDED
