#ifndef FUNCIONESRESERVA_H_INCLUDED
#define FUNCIONESRESERVA_H_INCLUDED

/// PROTOTIPOS DE FUNCIONES PARA EL MENU RESERVAS
void registrarReserva();


void listarReservas();
#endif // FUNCIONESRESERVA_H_INCLUDED
